---
contests:
- state representative:
    tally: plurality
    choices:
    - name: 71 72
      party: Circle Party
    - name: 73 74
      party: Triangle Party
- state senate:
    tally: plurality
    choices:
    - name: 75 76
      party: Circle Party
    - name: 77 78
      party: Triangle Party
- mayor:
    tally: plurality
    choices:
    - name: 79 80
      party: Circle Party
    - name: 81 82
      party: Triangle Party
    - name: 83 84
      party: Triangle Party
    - name: 85 86
      party: Pentagon Party
    - name: 87 88
      party: Rectangle Party
- alderman ward 1:
    tally: plurality
    choices:
    - name: 89 90
      party: Rectangle Party
    - name: 91 92
      party: Circle Party
    - name: 93 94
      party: Triangle Party
- alderman ward 2:
    tally: plurality
    choices:
    - name: 95 96
      party: Rectangle Party
    - name: 97 98
      party: Circle Party
    - name: 99 100
      party: Triangle Party
- alderman ward 3:
    tally: plurality
    choices:
    - name: 101 102
      party: Rectangle Party
    - name: 103 104
      party: Circle Party
    - name: 105 106
      party: Triangle Party
- Question 1 - accept Pine Street as an official town road:
    tally: plurality
    win-by: 1/2
    choices:
    - yes
    - no
- Question 2 - hire a sustainability person:
    tally: plurality
    win-by: 1/2
    choices:
    - yes
    - no
voting centers:
- Alum Rock Center:
    street: 4321 A Street
    id: 000002
submodules: []
