---
contests:
- alderman ward 2:
    tally: rcv
    choices:
    - name: Q One Two
      party: Rectangle Party
    - name: W Two Three
      party: Triangle Party
    - name: e Foo Four
      party: Circle Party
- Question 1 - paint firehydrants red:
    tally: plurality
    choices:
    - yes
    - no
- Question 2 - paint water tower red:
    tally: plurality
    win-by: 2/3
    choices:
    - yes
    - no
voting centers:
- Oakland Library Center:
    address: 4321 Foo Street
    id: 000012
submodules: []
