---
contests:
- state representative:
    tally: plurality
    choices:
    - name: Aaa Aaa
      party: Circle Party
    - name: Bbb Bbb
      party: Triangle Party
- state senate:
    tally: plurality
    choices:
    - name: Ccc Ccc
      party: Circle Party
    - name: Ddd Ddd
      party: Triangle Party
- mayor:
    tally: rcv
    choices:
    - name: Eee Eee
      party: Circle Party
    - name: Fff Fff
      party: Triangle Party
    - name: Ggg Ggg
      party: Triangle Party
    - name: Hhh Hhh
      party: Rectangle Party
    - name: Iii Iii
      party: Pentagon Party
- alderman ward 1:
    tally: rcv
    choices:
    - name: Jjj Jjj
      party: Rectangle Party
    - name: Kkk Kkk
      party: Triangle Party
    - name: Lll Lll
      party: Circle Party
- alderman ward 2:
    tally: rcv
    choices:
    - name: Mmm Mmm
      party: Rectangle Party
    - name: Nnn Nnn
      party: Circle Party
    - name: Ooo Ooo
      party: Triangle Party 
- alderman ward 3:
    tally: rcv
    choices:
    - name: Ppp ppp
      party: Rectangle Party
    - name: Qqq Qqq
      party: Pentagon Party
    - name: Rrr Rrr
      party: Circle Party
- Question 1 - school budget override:
    tally: plurality
    choices:
    - yes
    - no
- Question 2 - new firehouse land purchase:
    tally: plurality
    win-by: 3/5
    choices:
    - yes
    - no
voting centers:
- Milpitas Senior Center:
    address: 4321 C Street
    id: 000006
submodules: []
